"""add telegram user identity

Revision ID: 88b5acd035b9
Revises: 0ff65b00fae0
Create Date: 2026-08-21 20:16:23.778990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b5acd035b9'
down_revision: Union[str, Sequence[str], None] = '0ff65b00fae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_user_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'telegram_user_id')
    # ### end Alembic commands ###
